name: reactive_keyboard
version: 0.1.9
author: Chris Jones
description: Helper library for handling Keyboard streams.
dependencies:
  browser: any
  merge_all:
    git: https://github.com/cajurabi/dart-merge-all.git
  observe: any
